#!/bin/sh

STORAGE=/lustre/cms/store/user/caputo/HHbbtautau/Run2

if [ $# -lt 3 ] ; then
    echo "Usage: $0 file_list_path output_folder sampleType [Spring15MC, Run2015B, Run2015C, Run2015D] python_cfg"
    echo "Choose between this folder: "
    ls -d $STORAGE*
    exit
fi

WORKING_PATH=$PWD
FILE_LIST_PATH=$1
OUTPUT_FOLDER=$2
LUSTRE_PATH=$STORAGE/$OUTPUT_FOLDER
SAMPLE_TYPE=$3
EXE_NAME=$4

if [ ! -d "$LUSTRE_PATH" ];then
	mkdir -p $LUSTRE_PATH
fi

ARCH=$SCRAM_ARCH

JOB_LIST=$( find $WORKING_PATH/$FILE_LIST_PATH -maxdepth 1 -name "*.txt" -print0 | xargs -0 -n 1 basename | sed "s/\.txt//" )

if [ "x$JOB_LIST" = "x" ] ; then
	echo "ERROR: directory '$FILE_LIST_PATH' does not contains any job description."
	exit
fi

for NAME in $JOB_LIST
do
    qsub -q local -l walltime=40:00:00 -N $NAME -o $LUSTRE_PATH -e $LUSTRE_PATH -v WORKSPACE=$WORKING_PATH,ARCH=$ARCH,PROGRAMM=$WORKING_PATH/$EXE_NAME,NAME="$NAME",SampleType=$SAMPLE_TYPE,OUTPUT_PATH="$LUSTRE_PATH",FILE_LIST=$FILE_LIST_PATH$NAME.txt microAODProduction/batchSub/batchSubmission.pbs
done
